version: '3.0'
services:
  jwks_server:
    image: nginx:alpine  
    restart: always
    #bind host port 8180 to container port 8080
    ports:
      - 8180:80
    volumes:
      - ./jwks_server/html:/usr/share/nginx/html/
    