version: '3.0'
services:
  bulk-fhir-client:
    image: bulk-fhir-client:latest
    restart: always
    ports:
      - 5000:80
  bulk-fhir-server:
    image: bulk-fhir-server:latest
    restart: always
    ports:
      - 5001:8080