version: '3.0'
services:
  jwks-server:
    image: jwks-server:latest
    build: 
      context: jwks_server
    restart: always
    ports: 
      - 8180:80
  bulk-fhir-client:
    image: bulk-fhir-client:latest
    build: 
      context: bulk_fhir_client
    restart: always
    ports:
      - 5000:80
  bulk-fhir-server:
    image: bulk-fhir-server:latest
    build: 
      context: bulk_fhir_server
    restart: always
    ports:
      - 5001:8080