version: '3.0'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: bulk_fhir_datastore
      MYSQL_USER: doctor*who
      MYSQL_PASSWORD: cyber*men
  jwks-server:
    image: jwks-server:latest
    build: 
      context: jwks_server
    restart: always
    ports: 
      - 8180:80
  bulk-fhir-client:
    image: bulk-fhir-client:latest
    build: 
      context: bulk_fhir_client
    restart: always
    ports:
      - 5000:80
  bulk-fhir-server:
    environment:
      - CORS_ORIGIN=https://cs6440-f18-prj20.apps.hdap.gatech.edu
    image: bulk-fhir-server:latest
    build: 
      context: bulk_fhir_server
    restart: always
    ports:
      - 5001:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bulk_fhir_datastore?useSSL=false&&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: doctor*who
      SPRING_DATASOURCE_PASSWORD: cyber*men
    depends_on:
      - "mysql"
  bulk-fhir-curator:
    image: bulk-fhir-curator:latest
    build: 
      context: bulk_fhir_resource_curator
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bulk_fhir_datastore?useSSL=false&&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: doctor*who
      SPRING_DATASOURCE_PASSWORD: cyber*men
    depends_on:
      - "mysql"
      
